apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: local/mssql/server:2022
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1.0"
          ports:
            - containerPort: 1433
          env:
            - name: User_Id
              value: "sa"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Sfr1376."
            - name: Trust_Server_Certificate
              value: "True"
            - name: Encrypt
              value: "False"
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqldb
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: mssql
  ports:
    - name: mssql
      protocol: TCP
      port: 1433
      targetPort: 1433
