apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-mockup-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redditmockup
  template:
    metadata:
      labels:
        app: redditmockup
    spec:
      containers:
        - name: redditmockup
          image: localhost/reddit-mockup-web:1.0
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1.0"
---
apiVersion: v1
kind: Service
metadata:
  name: reddit-mockup-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: redditmockup
  ports:
  - name: redditmockup
    protocol: TCP
    port: 6000
    targetPort: 80
  - name: redditmockup-https
    protocol: TCP
    port: 6001
    targetPort: 443